### ISSUE TITLE
Failure to open files

### ISSUE THREAD

**Issue by Kabouik** [VladimirMikulic/visum#1]
I stumbled upon your project while looking for a lightweight .doc viewer (I was not specifically looking for something based on Microsoft Office online, just wanted something lighter than LibreOffice). This looks like a really awesome project, thanks for your work! I really like it. I still have to check if it requires an Internet connection (I guess it does) and what is the CPU use for Microsoft Office online, but I definitely want to have this installed on my computer.

However, I'm facing an issue opening files right now. I installed `visum` using the install script and associated files are now in `/usr/share` as they should, but nothing happens when I try to open a file from a GUI file browser with `visum`. Same from command line: I noticed that `/usr/share/visum/scripts/visum.sh` is not executable, but if I `cd /usr/share/visum` and then run it with `sh scripts/visum.sh path/to/file.doc`, I get this:

```bash
/usr/share/visum $ sh scripts/visum.sh /path/to/file.doc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    258      0 --:--:-- --:--:-- --:--:--   258
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
scripts/visum.sh: command substitution: line 46: syntax error near unexpected token `('
scripts/visum.sh: command substitution: line 46: `comm -23 <(seq 49152 65535 | sort) <(ss -Htan | awk '{print $4}' | cut -d':' -f2 | sort -u) | shuf | head -n 1'
Bad remote forwarding specification 'vu8QnGxX90:80:localhost:'

```

Other than that, I find it a bit weird that `install.sh` moves everything clone from git to `/usr/share/visum`, including files that are probably not needed to execute `visum`. I would expect that only mandatory files for execution would be moved there, while other files (`LICENSE.md`, `install.sh`, _etc._) would stay in the git folder.

**Comment by Kabouik** [comment]
Making the script executable with `sudo chmod +x` and then executing it with `scripts/./visum.sh /path/to/file.doc` changes the output:

```bash
/usr/share/visum $ scripts/./visum.sh /path/to/file.doc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    223      0 --:--:-- --:--:-- --:--:--   223
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Forwarding HTTP traffic from https://ggheresfsdfaap2sdfq.serveousercontent.com
Server is running on PORT 56304
```

However, it doesn't automatically open a tab, and manually going to the URL (which I changed here just in case) doesn't work because it never ends loading in the browser. Also, the format `URL:port` fails immediately.

**Comment by VladimirMikulic** [comment]
Hi @Kabouik!
Thank you very much for your kind words and for reporting this issue.
I am not at home right now, but as soon as I return, I'll get hands on this!

**Comment by VladimirMikulic** [comment]
@Kabouik I am back again with answers.
Sorry for the waiting time. From your Github profile, I can tell that you are a tech guy and not an ordinary customer so I'll get straight to the facts :)

As you already know, Visum opens your Office files in the browser.
To be able to do this, your file needs to be accessible on the internet so Microsoft's Office can fetch it and display it to you.
I use port forwarding service - `serveo` for this which seems to be down at the moment.

I guess I'll need to replace `serveo` with a more stable tool like `ngrok`.
The primary goal of Visum is being fast & lightweight to install, that's why I've chosen `serveo`.

**Comment by VladimirMikulic** [comment]
> Other than that, I find it a bit weird that install.sh moves everything clone from git to /usr/share/visum, including files that are probably not needed to execute visum. I would expect that only mandatory files for execution would be moved there, while other files (LICENSE.md, install.sh, etc.) would stay in the git folder.

You are absolutely right! While writing `install.sh` the easiest option was to copy everything and save a few lines (creating visum directory in `/usr/share` folder, copying specific dirs/files etc.). I'll make sure to update the installer as well.

**Comment by Kabouik** [comment]
Thanks for the follow-up @VladimirMikulic. That explains why manually going to the URL doesn't work. Shouldn't `visum` try to open a tab anyway though?

I didn't know `serveo`, interesting alternative to `ngrok`! Unfortunately, looking at the issues, it seems that the server is very often down (sometimes for several weeks/months) and that it has been like this since several years, which makes it impossible to count on it sadly. 
 
> From your Github profile, I can tell that you are a tech guy and not an ordinary customer

Ha! Not really, I'm not in programming at all, just a regular Linux user interested in learning more!

**Comment by VladimirMikulic** [comment]
Hi @Kabouik.
Thank you for waiting. I've replaced `serveo` and Visum is ready!
Enjoy :rocket:

**Comment by Kabouik** [comment]
Excellent, thanks a lot! I'll give it a try.

My first attempt failed with this error: `./scripts/visum.sh: line 66: x-www-browser: command not found`, which I guess might be related to the WM I'm using (i3) or the mime handler?

Note also that the `visum.sh` script placed in `/usr/share/visum/scripts/` during install was still not executable. I had to `chmod +x` it. But perhaps a better way would be to move this script it to `/usr/local/bin/visum` anyway so that the `visum` command exists in the `$PATH`. If I understand correctly the code, some minor modifications would have to be done to the script itself to use the absolute path on line 71 instead of the relative path, as currently it seems `visum.sh` needs to be called from `/usr/share/visum` for `python3 scripts/server.py $PORT &` to find `server.py`.

**Comment by VladimirMikulic** [comment]
Hi @Kabouik.
I haven't seen "`x-www-browser` command not found" for a long time.
It's pretty much a standard these days, but I guess it has something to do with your setup.
Do you have `xdg-open` command?

Regarding your second issue, Visum is not available to use as a CLI at the moment.
That's partly because of `.desktop` file and the environment in which scripts are executed but also because of big text output that it produces by running all these commands.

What do you think? Would you use it more often via CLI than GUI/Keyboard shortcut?

Thanks a lot for your feedback.

**Comment by Kabouik** [comment]
I have `xdg-open` but I actually use `handlr` as my mime handler, perhaps this is the cause. Do you know if there is any standard way to launch the default browser across all the numerous mime handlers?

I would definitely use `visum` from CLI most of the time since I use a terminal email client (`nmail`, which opens files with their default application through `handlr` anyway, but having a command line available would allow some scripting) and a terminal file manager (`nnn`). But even for users not spending this much time in the terminal, I believe being able to execute from the command line is a common expectation, at least to debug, make aliases or script things to their liking. Perhaps I underestimate the amount of work that it would require though, I'm no programmer at all, so far this line 71 is the only thing I noticed where the path would need to be absolute, but I have no idea what other environment requirements would change.

As for the terminal output when executing from command line, this can also be hidden on demand if with WMs that have a swallowing feature (or alternatively, with [`devour`](https://github.com/salman-abedin/devour) which is WM-agnostic).

**Comment by VladimirMikulic** [comment]
That's great. By executing `xdg-open <office_file` Visum will open your file.
There is a lot of output which can hardly be suppressed since bash language is not designed for complicated states.
A nice workaround here would be to redirect output manually like this:
`xdg-open <office_file> > /dev/null 2>&1` -> no long CLI output

Typing this every time would be cumbersome, so you could create an alias function (.bashrc/.zshrc):
```bash
visum() {
  xdg-open $1  > /dev/null 2>&1
}
```
Now, you can type `visum <office_file>` and you are good to go!
I should include this in README. It's the cleanest way to run Visum from CLI.

You could create an alias for `x-www-browser` as well (.bashrc/.zshrc):
`alias x-www-browser=xdg-open`

Let me know if this worked for you.

**Comment by Kabouik** [comment]
Somehow executing `xdg-open file.docx` (the vanilla `xdg-open`, not my `handlr` script) defaults to Libreoffice, and even if I change the default in Nautilus to Visum, then I just get a new tab in Firefox to download the .docx file, not to open it with the online editor (I don't think it calls `visum.sh` at all). I never was comfortable with how mime applications works and where they take their default, it's a mess, which is exactly why I moved to `handlr` for easier customization of default apps!

With my custom `handlr` script named `xdg-open`, I can see that it calls `visum.sh` because I see some temporary files being created by Visum in `/tmp/`, but no new tab in the brwoser, which I think is this `x-www-browser` not found again, and creating the `x-www-browser` alias as you suggested doesn't help. I assume it would call the `handlr` script again and therefore just loop through it when `visum.sh` calls `x-www-browser`, no?

I'm sorry if these issues might be related to my own environment.

**Comment by VladimirMikulic** [comment]
Hi @Kabouik.
No need to apologize, it's not your fault. Linux is just... messy :)
Could you open `visum.sh` and replace `x-ww-browser` with `xdg-open` command?
`xdg-open` should launch a browser.

Thank you for your patience.

**Comment by Kabouik** [comment]
I modified `visum.sh` and now vanilla `xdg-open` indeed opens a new tab when Visum is set as the default application in Nautilus, but I get this:

![ss-2020-07-12_181744](https://user-images.githubusercontent.com/7107523/87251441-54ae5280-c45b-11ea-8730-c201636b0089.png)

And this is the terminal output 
```
/usr/bin/xdg-open /tmp/bgfr_draft-0.1.docx 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     54      0 --:--:-- --:--:-- --:--:--    54
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Server is running on PORT 61485

===============================================================================
Welcome to localhost.run!

Head over to https://twitter.com/localhost_run and give us a follow for the
hottest SSH port forwarded local dev env news.

**You need a SSH key to access this service.**

If you don't know what this is pls don't panic, you're smart, you've got this.
Github has a great howto, follow along with it to get prepared for the change:
https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**If you see a message below telling you that your hostname is already in use**
** try a different username like this:**
**`ssh -R localhost:80:localhost:8080 random-string@ssh.localhost.run`**
===============================================================================

127.0.0.1 - - [12/Jul/2020 18:17:36] "GET /tmp/bgfr_draft-0.1.docx?key=[redacted] HTTP/1.1" 400 -

```

With my `handlr open "$@"` script to replace `xdg-open`, still no tab opening.

**Comment by Kabouik** [comment]
Actually my `handlr` script managed to open a tab just now (with the same file not found error), but then I closed the tab and tried again, and I couldn't reproduce. It doesn't show any output in the terminal so I don't know what changed between both attempts.

**Comment by VladimirMikulic** [comment]
Thanks a lot, @Kabouik.
After some troubleshooting, it seems that `x-www-browser` and `xdg-open` commands don't open the browser in the same way. 
This causes the issue. I'll try to make `xdg-open` work and will replace `x-www-browser` with it.

**Comment by VladimirMikulic** [comment]
It is really weird how those mime-types are handled and how default applications are launched, but I think I got it this time.

Could you please try to install Visum again?
If you don't mind, could you tell me your distro version and the default browser? (please check if `xdg-settings` command is available)

Thank you.

**Comment by Kabouik** [comment]
> It is really weird how those mime-types are handled and how default applications are launched, but I think I got it this time.

Yeah from a non-programmer perspective, it's a real mess. I'm sure there is a logic to it, but from what I saw in other projects, even developers have headaches trying to understand it. This is where `handlr` is actually very cool, it makes everything much simpler.

I just tried the update, now everytime I call `xdg-open file.docx`, it opens a tab in Firefox but offers to download the file, as if `visum` was skipped. This is the output in terminal:

```
/usr/bin/xdg-open /tmp/bgfr_draft-0.1.docx 
/bin/bash: scripts/visum.sh: No such file or directory
/usr/bin/xdg-open: line 875: x-www-browser: command not found
```
If I understand correctly, the vanilla `xdg-open` also tries to call `x-www-browser` but can't find it?

 If I try to open a file in Nautilus with `visum`, nothing happens. Finally, my custom `handlr` replacement script doesn't seem to do anything, similar to when opening a file from Nautilus. 

`xdg-settings get default-web-browser | awk -F "." '{print $1}'` alone works and returns `userapp-Firefox-XGT2G0`. 

My system is Solus distribution, and Firefox is indeed my default browser.

**Comment by VladimirMikulic** [comment]
> If I understand correctly, the vanilla xdg-open also tries to call x-www-browser but can't find it?

Well, this makes things even weirder.
`x-www-browser` command works on my system, but `xdg-open` opens the tab with "File not found error".

The good thing is that I've introduced this `xdg-settings` which should return string/command for the default browser.
On my end (Kubuntu 20.04) it simply returns `firefox` which opens the link successfully.
I thought that should be cross-distro compatible but it seems that it's not.

I guess running `userapp-Firefox-XGT2G0` in your terminal would produce command not found.
Could you confirm this statement?

For a non-programmer you are a great help @Kabouik.
I am sorry for putting you through so much troubleshooting.

**Comment by VladimirMikulic** [comment]
Hi @Kabouik.
I've just realized that you were running old version of Visum. (I thought I've pushed changes on Github but apparently I haven't)
Today I installed Solus in a virtual machine to test Visum with new changes and it works!

Thank you & let me know how the things are on your end.

**Comment by Kabouik** [comment]
Thanks for following up @VladimirMikulic! Sadly the issue is still here:

```
~/.config $ /usr/bin/xdg-open /tmp/bgfr_draft-0.1.docx 
/bin/bash: scripts/visum.sh: No such file or directory
/usr/bin/xdg-open: line 875: x-www-browser: command not found
```
Firefox is opening a new tab to offer me to download the file, not to view/edit it.

And using my custom `handlr open "$@"` in `~/.local/bin/xdg-open` instead of the vanilla `/usr/bin/xdg-open` script does nothing.

Surely there must be something broken on my hand if it works in your VM, but I'm not sure where to look.

Other than that, I can confirm `userapp-Firefox-XGT2G0` is not a recognized command in bash.

**Comment by VladimirMikulic** [comment]
No problem @Kabouik, we'll resolve this.
Could you tell me the output of this line on your machine `xdg-mime query default x-scheme-handler/https`?

Thanks.

**Comment by Kabouik** [comment]
`userapp-Firefox-XGT2G0.desktop`, which is located in `~/.local/share/applications`. There is a `/usr/share/applications/firefox.desktop` too, but the command you posted didn't list it.

**Comment by VladimirMikulic** [comment]
I see. This is probably due to custom mime-type handler (`handlr`), but I believe you are not the only one using it so I've created a simple condition in the script to recognize this type.
Make sure to pull the new version of Visum and let me know if I've squashed the bug :)

**Comment by Kabouik** [comment]
Still no luck but I'm not sure this is a new version because the git history shows contradicting modification dates:

![ss-2020-07-13_112357](https://user-images.githubusercontent.com/7107523/87288269-a94cde80-c4ea-11ea-9461-f977e8f136e5.png)
![ss-2020-07-13_112348](https://user-images.githubusercontent.com/7107523/87288272-a9e57500-c4ea-11ea-97b0-69e248b87f57.png)

**Comment by VladimirMikulic** [comment]
It is a new version. You can take a look at the source and compare it. (`visum.sh` line 72)
```sh
  if [[ $DEFAULT_BROWSER == *"-"* ]]; then
    DEFAULT_BROWSER=`echo $DEFAULT_BROWSER | awk -F '-' '{print $2}' | tr '[:upper:]' '[:lower:]'`
  fi
```

I didn't add an additional commit (snapshot of change). Instead, I've appended it to the last commit to keep it clear. (for me - the programmer)

**Comment by Kabouik** [comment]
Thanks for clarifying. This is indeed the `visum.sh` I have, but same output as before unfortunately with the normal `xdg-open`:

```
/usr/bin/xdg-open: line 875: x-www-browser: command not found
```
And it opens a tab to download the file. It seems `visum` is still trying to use `x-www-browser`, because line 875 in `/usr/bin/xdg-open` is just a variable:

```
open_envvar()
{
    local oldifs="$IFS"
    local browser browser_with_arg

    IFS=":"
    for browser in $BROWSER; do
        IFS="$oldifs"

        if [ -z "$browser" ]; then
            continue
        fi

        if echo "$browser" | grep -q %s; then
            # Avoid argument injection.
            # See https://bugs.freedesktop.org/show_bug.cgi?id=103807
            # URIs don't have IFS characters spaces anyway.
            has_single_argument $1 && $(printf "$browser" "$1")
        else
            $browser "$1"  ### <-- This is line 875
        fi

        if [ $? -eq 0 ]; then
            exit_success
        fi
    done
}
```

Nothing happens when opening from Nautilus with `visum` set as default, or using `handlr`.

**Comment by VladimirMikulic** [comment]
That's odd. This was the plan:
`xdg-settings get default-web-browser | awk -F "." '{print $1}'` returns `userapp-Firefox-XGT2G0` just as you said.
Then, the `if` condition runs and extracts `firefox` from that string.

Lastly, `firefox <url>` command runs which should open your default browser - firefox.
Could you please modify `/usr/share/visum/scripts/visum.sh` and put `echo $DEFAULT_BROWSER` after the if statement (line 72) and report the result to me. (it should output `firefox`)

Lastly, do you have a TeamViewer set up? If you agree, of course, I would be willing to connect to your machine and troubleshoot Visum myself. I am afraid that this is the only way we can make it work for you. (if you have some doubts, you will be able to watch me the whole time :)

Let me know what you think.

**Comment by Kabouik** [comment]
Unfortunately that's not possible because this is a work computer and I currently am on the work network, this wouldn't be tolerated if they'd knew. I know how frustrating that can be because I myself was in that position, asking people if they'd allow me solving their issue remotely because I knew it would be faster and easier, and it's always frustrating when it is not possible. :/

I've edited the script as you said, but I think there might be something we have overlooked in the above logs:

```
$ /usr/bin/xdg-open /tmp/bgfr_draft-0.1.docx 
/bin/bash: scripts/visum.sh: No such file or directory
/usr/bin/xdg-open: line 875: x-www-browser: command not found
```

I don't think I had this issue with `visum.sh` not being found at the very beginning when I opened this issue, but looking at our discussion here, it's here [since a few updates now](https://github.com/VladimirMikulic/visum/issues/1#issuecomment-657254693).

I can confirm the script is in `/usr/share/visum/scripts/`:

```
$ tree /usr/share/visum
/usr/share/visum
├── media
│   ├── visum_logo.svg
│   ├── visum_promo_excel.gif
│   └── visum_promo.mp4
└── scripts
    ├── server.py
    └── visum.sh

2 directories, 5 files
```

Turns out it is again because I need to `sudo chmod +x /usr/share/visum/scripts/visum.sh` after installing, othwerwise it'll fail to execute the script and therefore probably just try to open the .docx file directly with `xdg-open`, resulting in Firefox offering me to download the file. Probably something to fix in the install script?

I've put the `x` flag on `/usr/share/visum/scripts/visum.sh` again and now I can confirm the  `echo` line we've just added returns `firefox`. Most importantly, `visum` is opening a tab again, both from real `xdg-open` and from the `handlr` script, which is good news. In both cases, however, I still get the "file not found" shown in a screenshot above.

**Comment by VladimirMikulic** [comment]
Nevermind, I'll try my best to fix it this way :)

> I've put the x flag on /usr/share/visum/scripts/visum.sh again and now I can confirm the echo line we've just added returns firefox.

Awesome! This proves that my code works and that browser is identified correctly!
Also, you don't need to `chmod +x visum.sh`. This file wasn't supposed to be executed directly.
Please check out "CLI" section in the README [here](https://github.com/VladimirMikulic/visum#%EF%B8%8F-cli).

**Comment by VladimirMikulic** [comment]
It would be useful to run `rm /tmp/visum_*` to clear old files once you are trying out a new version.

**Comment by Kabouik** [comment]
I do use the alias but I'm still getting this error when using `xdg-open` (or `handlr`):

```
$ /usr/bin/xdg-open /tmp/bgfr_draft-0.1.docx 
/bin/bash: scripts/visum.sh: No such file or directory
/usr/bin/xdg-open: line 875: x-www-browser: command not found
```

Of course with the alias, `visum file.docx` in terminal works (*i.e.*, it opens a new tab, but it still shows "File not found"), but I assume we would need mime openers to work as well for use from other applications. Wouldn't using absolute path instead of relative fix this?

> It would be useful to run `rm /tmp/visum_*` to clear old files once you are trying out a new version.

Good to know, thanks. I tried that with a fresh install of `visum` but no change.

**Comment by VladimirMikulic** [comment]
Hi @Kabouik.
`xdg-open`/`handlr` won't work, that's why I made a CLI section which includes a workaround this issue.
The good news is that it works even on your environment :)

Could you please run `bash /usr/share/visum/scripts/visum.sh <path_to_your_office_file>` and report the log to me?

Thanks.

**Comment by Kabouik** [comment]
> Could you please run `bash /usr/share/visum/scripts/visum.sh <path_to_your_office_file>` and report the log to me?
```
~ $ bash /usr/share/visum/scripts/visum.sh /tmp/bgfr_draft-0.1.docx 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    250      0 --:--:-- --:--:-- --:--:--   250
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
python3: can't open file 'scripts/server.py': [Errno 2] No such file or directory

===============================================================================
Welcome to localhost.run!

Head over to https://twitter.com/localhost_run and give us a follow for the
hottest SSH port forwarded local dev env news.

**You need a SSH key to access this service.**

If you don't know what this is pls don't panic, you're smart, you've got this.
Github has a great howto, follow along with it to get prepared for the change:
https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**If you see a message below telling you that your hostname is already in use**
** try a different username like this:**
**`ssh -R localhost:80:localhost:8080 random-string@ssh.localhost.run`**
===============================================================================

connect_to localhost port 49355: failed.
```
I have a ssh key added to my ssh-agent.

Now if I run `visum.sh` directly, there are fewer errors in the output about scripts not being found, but I still get a "File not found" tab:
```
/usr/share/visum $ ./scripts/visum.sh /tmp/bgfr_draft-0.1.docx 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    283      0 --:--:-- --:--:-- --:--:--   288
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Server is running on PORT 63490

===============================================================================
Welcome to localhost.run!

Head over to https://twitter.com/localhost_run and give us a follow for the
hottest SSH port forwarded local dev env news.

**You need a SSH key to access this service.**

If you don't know what this is pls don't panic, you're smart, you've got this.
Github has a great howto, follow along with it to get prepared for the change:
https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**If you see a message below telling you that your hostname is already in use**
** try a different username like this:**
**`ssh -R localhost:80:localhost:8080 random-string@ssh.localhost.run`**
===============================================================================

127.0.0.1 - - [15/Jul/2020 11:18:11] "GET /tmp/bgfr_draft-0.1.docx?key=[redactedip] HTTP/1.1" 400 -
```

>  `xdg-open`/`handlr` won't work, that's why I made a CLI section which includes a workaround this issue.

This is really confusing to me, maybe there is something I didn't understand. Don't we need `visum` to be callable from mime openers to make it the default application and work when opening a file from any other application? I don't understand how I can make `visum` the default if it can't work from `xdg-open`, but I'm sure this is just me missing something here, sorry if I'm asking you to explain basics!

**Comment by VladimirMikulic** [comment]
Alright, we are onto something, nice job :+1: 
It seems that the python3 server is not started.

> I don't understand how I can make visum the default if it can't work from xdg-open, but I'm sure this is just me missing something here, sorry if I'm asking you to explain basics!

The thing is that `xdg-open` can behave strangely and it's not reliable to use it as it is. (CLI section as a clean solution)
This is not your fault. It is a bit strange though that `bash /usr/share/visum/scripts/visum.sh <path_to_your_office_file>` resulted in an error. This is probably an environment issue because I've tested this on multiple VMs.

On the other hand, your second try works. (`./scripts/visum.sh /tmp/bgfr_draft-0.1.docx`)
The last line is from the python3 server and shows 400 code which means that either the file is invalid or key. (the key is your public IP)
I doubt it's the key, it's probably an issue with mime-type.

Could you please run `python3 -c "import mimetypes; print(mimetypes.guess_type('/tmp/bgfr_draft-0.1.docx')[0])"
` and report me the result.

Thanks.

**Comment by Kabouik** [comment]
But the difference in the two outputs I posted is just the present working directory from which I execute the script. Since `server.py` is referred to with its relative path in `visum.sh`, it is found only if I'm already in `/usr/share/visum` when executing `visum.sh`, not if I do `bash /usr/share/visum/scripts/visum.sh /tmp/bgfr_draft-0.1.docx` from elsewhere.

Further testing confirms the same issue even with `xdg-open` and `handlr open`: if I run `xdg-open /tmp/file.docx` from elsewhere, it fails (just a tab offering to download file.docx); if I run the same command while being in `/usr/share/visum`, then `visum` actually succeeds and tries to display the file (still with the "File not found" issue, but at least it's not failing to start the server). Same with `handlr`: it "works" ("File not found") when run from `/usr/share/visum`, and doesn't when run from elsewhere, probably just because this will change whether `visum.sh` finds `server.py` or not.

`python3 -c "import mimetypes; print(mimetypes.guess_type('/tmp/bgfr_draft-0.1.docx')[0])"` returns "None", also confirmed with other docx files, so there's definitely a mimetype error too indeed.

**Comment by VladimirMikulic** [comment]
Thanks a lot, @Kabouik.
I have something in mind for server.py in your environment, but that will need to wait.
Now, we finally know the root cause of the issue. Mimetype results in `None` which makes server return 400 (invalid request).
This serves as a filter. For some reason, python doesn't recognize your Docx file as an Office file.

How did you obtain this file? Have you created it yourself, if so, in which app? (native MS Office on Windows, MS Office Online, Libre Office etc.)

Once we resolve this, I'll make a change to the script to get the right path in different environments.

Thanks a lot!

**Comment by Kabouik** [comment]
Nothing special about the docx file, I tried several before answering here actually to make sure this wouldn't be specific to a wrongly formatted file. Therefore, I tried (1) pandoc-generated docx files, (2) docx files created in LibreOffice, (3) and docx files I received by email and I am 98% sure they were created with MS Office. "None" in all cases.

**Comment by VladimirMikulic** [comment]
That's weird. Could you try `mimetype <your_office_file>` and see what it returns?

**Comment by Kabouik** [comment]
I don't have the mimetype command, not sure what package it depends on. However, `file file.docx` returns `Microsoft Word 2007+` for all the files I've tested. Also, 

```
$ xdg-mime query filetype /tmp/bgfr_draft-0.1.docx 
application/vnd.openxmlformats-officedocument.wordprocessingml.document
```

**Comment by VladimirMikulic** [comment]
`mimetype` is built-in on most of the distros, but I guess it's not on Solus. At least `file` command works. I'll modify existing python code to use the `file` command to be more cross-distro compatible.

I'll get back in a few minutes.

**Comment by VladimirMikulic** [comment]
It took a bit longer than I expect, but you should be good to go now with `./scripts/visum.sh /tmp/bgfr_draft-0.1.docx`.
The next step is server path (once you confirm that this works for you, of course :)

Great job & don't forget to pull new changes.

**Comment by Kabouik** [comment]
Yup, I can confirm the file now shows up properly when I `cd /usr/share/visum` then `bash scripts/visum.sh file.docx` (`./scripts/visum.sh` won't execute if I don't `chmod +x` first, so I used `bash`).

Same with `/usr/bin/xdg-open file.docx`, `xdg-open file.docx` (which is my `handlr open` custom script replacement) and directly `handlr open file.docx`, but only when they're run from `/usr/share/visum` as discussed above. :+1:

**Comment by VladimirMikulic** [comment]
We did it! Glad it is finally working for you.
I've fixed the issue with the path to work in both, GUI and CLI. (absolute)

Might be a minor problem when I package Visum in Snap/Appimage but that's a problem for another day!

Thank you for all the feedback, it's been really useful. I wish more people were as skilled as you.
Nice job as always and don't forget to pull new changes :)

**Comment by Kabouik** [comment]
Actually, I'm sorry to say that the issue persists for me even with your latest commit to change paths to absolute: `xdg-open` and `handlr-open` still work only if executed when I am already in a terminal at `/usr/share/visum`, otherwise `xdg-open` still reports the following:

```
$ /usr/bin/xdg-open /tmp/bgfr_draft-0.1.docx 
/bin/bash: scripts/visum.sh: No such file or directory
/usr/bin/xdg-open: line 875: x-www-browser: command not found
```

Yet, I can confirm that my `/usr/share/visum/scripts/visum.sh` is the latest version, as it contains this on L80:
```
python3 /usr/share/visum/scripts/server.py $PORT &
```

`handlr open` doesn't show any terminal output but I am pretty sure the issue is the same. 

I deleted `/usr/share/visum/` and `/tmp/visum*` before pulling the new commit and reinstalling `visum`. I suspect the issue is with the `.desktop` file which still contains `Exec=bash scripts/visum.sh %f`. Maybe add some lines in the README to list all the files that should be manually deleted before upgrading, or make sure the script automates that?

**Comment by Kabouik** [comment]
Actually, the desktop file was not updated in your latest commit and it still contains this relative path, ~~which causes the issue. This works:~~

```
[Desktop Entry]
Type=Application
Name=Visum
Encoding=UTF-8
Path=/usr/share/visum
Exec=bash /usr/share/visum/scripts/visum.sh %f
Icon=/usr/share/visum/media/visum_logo.svg
Comment=In-browser Office files viewer for Linux.
MimeType=application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;application/vnd.openxmlformats-officedocument.wordprocessingml.document;application/vnd.openxmlformats-officedocument.presentationml.presentation
Terminal=false
Categories=Office;
```

[Edit] No, actually it doesn't solve the issue: 

```
~/.config $ /usr/bin/xdg-open /tmp/bgfr_draft-0.1.docx 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0    294      0 --:--:-- --:--:-- --:--:--   294
/usr/share/visum/scripts/visum.sh: line 39: x-www-browser: command not found
/usr/bin/xdg-open: line 875: x-www-browser: command not found
```
I'm really confused as to why it works when I'm in `/usr/share/visum` if the issue is with an unknown command on L39.

Also, there's **another problem** that I should perhaps report in another issue: closing the tab where the document is open does not kill the server process, which can become an issue when viewing several documents in a row if nothing kills the process when no longer used. Can you confirm this?

**Comment by VladimirMikulic** [comment]
Hi @Kabouik.
No problem, we'll resolve this as well.
Please see CLI section which describes how `visum` should be used in CLI. `xdg-open`/`handlr` are not ways to go hence the CLI section.

Regarding the server instance running, it's on purpose for better user experience.
This server process is reused. When you open another document, it'll take far less time to open your document, because there is no need to start a new instance. The server takes < 10mb of RAM which in my opinion, is a fair trade for a noticeable performance boost.

**Comment by Kabouik** [comment]
I use the `visum` alias too from CLI, I just was testing the mime openers to simulate how well it would work from GUI apps, but wanted the terminal output to see what would be the potential issues.

Actually, I have trouble consistently reproducing this issue. This is really weird. Sometimes, executing from a different folders works just fine (even with `xdg-open`/`handlr`, which I think is interesting), and other times it fails. Perhaps it is actually related to the server persisting for some time, and maybe in some occasions starting a new one works from anywhere, but resuming from a different directory doesn't work, or whatever? I didn't test any of this, just throwing ideas and fishing blindly here.

**Comment by VladimirMikulic** [comment]
That's weird. On my host Ubuntu + KDE (Kubuntu) it works just fine as well as in other VMs too.
The absolute path must work from anywhere unless `xdg-open`/`handlr` are blocking it to do so.

Have you tried running Visum in GUI like double-clicking the file or right-click "Open with Visum"?

**Comment by Kabouik** [comment]
My primary file manager is a terminal FM (which is why I was also interested in using `xdg-open`/`handlr` from terminal), but I did try from Nautilus too and actually the result is weird, because again I'm having inconsistent results: my first file (the one we tried all along here) opened a tab with "File not found", and another file recognized with the same mimetype didn't open a new tab.

I tried some other things afterwards and got those interesting results which indicate GUI never works (despite it being based on `xdg-open` I think) and CLI works only from `/usr/share/visum` regardless of the method I use (which I think contradicts some of the above posts, **so again, I can't reproduce the bug reliably**):

## From GUI
1. Got back to `/tmp` and put both files there: they both opened "File not found" tabs from the GUI.
2. Moved one of the files to `/usr/share/visum`, navigated there, tried to open the file: nothing happened.

## From CLI
1. `visum` alias works, but only from `/usr/share/visum`, otherwise it returns a file not found. 
2. Same for `xdg-open` and `handlr`, they work from `/usr/share/visum` but not elsewhere.

This is confusing, I'm sorry. But I am also having trouble debugging this by myself since I haven't found how to consistently reproduce and it's difficult from GUI with no error output.

**Comment by VladimirMikulic** [comment]
Hi @Kabouik.
I very much appreciate your insight on this issue.
You can view error output for GUI if you modify `/usr/share/applications/visum.desktop` file and set `Terminal=true`.
The default is `Terminal=false`, which is the reason why the terminal is not launched.

It is really weird that my solution in CLI section of the README doesn't work for you since there is no actual usage of `xdg-open`/`handlr`, just a regular browser command i.e. `firefox <document_url>`.

**Comment by Kabouik** [comment]
Actually the main problem is I get inconsistent results (which certainly means the issue is not on Visum's side but with my environment, also confirmed by you having no issues in VMs). I'll give it more time, maybe using it on a regular basis will allow narrowing down what is the issue on my side and how to reproduce. Thanks for your patience!

**Comment by VladimirMikulic** [comment]
No worries, take your time & thank you!
